### ISSUE TITLE
iterating over array property with jade templates?

### ISSUE THREAD

**Issue by simon-lang** [socketstream/ss-hogan#2]
Hi sorry I realise this is not actually an ISSUE, but I can't figure out the syntax for iterating over a property which is an array. e.g.

client.js

```
    html = ss.tmpl['game-full'].render({
      name: 'GTA IV',
      platforms: [{
          name: 'ps3'
        }, {
          name: 'xbox'
        }
      ]
    })
```

templates/game/full.jade

```
    h1 {{name}} is fine
    ul
      li I don't know how to list {{platforms}} here, one per li
```

I'm just a bit confused by the Jade>HTML>Hogan process I think, and not sure what syntax to use.

**Comment by paulbjensen** [comment]
This document might help. https://mustache.github.io/mustache.5.html. Please reopen if it still needs resolving.
